#!/bin/bash
# Use this if you get tired of restarting the program after every change/rebuild cycle :)

ARGS=$@
while true; do
	STAT=`stat synapse modules/*.module/*.so`
	#echo $STAT
	if [ "$STAT" != "$OLDSTAT" ]; then
		OLDSTAT=$STAT
		killall -9 synapse
		#sleep 1
		echo "############# PROGRAM CHANGED, RESTARTING #############"
		./synapse $ARGS &
	fi
	sleep 1 || exit 0
done
