#!/usr/bin/python

import argparse
parser=argparse.ArgumentParser(
    description='PODcast url getter 1.0',
    epilog='This creates .strm files that can be used to listen to podcasts with MediaZapper.')
parser.add_argument('feed',  help='Feed url')
args=parser.parse_args()



import feedparser
feed=feedparser.parse( args.feed )

import os.path
for entry in feed['entries']:
	for link in entry['links']:
		if link['rel'] == 'enclosure':
			strm_file=entry['title'] + ".strm"
			if not os.path.isfile(strm_file):
				print (entry['title'] + " -> " + link['href'])
				with open(strm_file, 'w') as f:
					f.write(link['href'] + "\n")
				break







